package com.pakvisualeditor.core

object FunctionReference {
    data class Item(val name: String, val meaning: String)
    val items = listOf(
        Item("ESP Master", "Main switch for the ESP display."),
        Item("Show AI", "Shows AI/bot entities in the ESP."),
        Item("Show Name", "Shows player names."),
        Item("Show Weapon", "Shows the held weapon."),
        Item("Show Team ID", "Shows the team identifier."),
        Item("Show Distance", "Shows distance to an entity."),
        Item("Box ESP", "Draws a box around a character."),
        Item("HP Bar", "Shows the health bar."),
        Item("Draw Distance", "Maximum ESP drawing distance."),
        Item("Rain / Snow / Black Sky", "Scene appearance options."),
        Item("No Fog / No Grass / No Trees / No Water", "Scene visibility options."),
        Item("White Body", "Changes character material appearance."),
        Item("Character Scale", "Character size controls."),
        Item("My Scale X/Y/Z", "Scale of the local character on each axis."),
        Item("Enemy Scale X/Y/Z", "Scale of other characters on each axis."),
        Item("Anti Gravity / Gravity", "Gravity-related parameters."),
        Item("Jump Height / Jump Boost", "Jump-related parameters."),
        Item("Speed / Speed %", "Movement speed parameters."),
        Item("Character Rotate / Rotate Speed", "Rotation parameters."),
        Item("Wall Climb / Lock Position", "Movement/position options."),
        Item("165 FPS", "Frame-rate related label in the source menu."),
        Item("iPad View / iPad FOV", "Camera/FOV presentation controls."),
        Item("Spring Arm / Arm Length", "Camera spring-arm distance controls."),
        Item("No Recoil / No ADS Recoil / Anti Shake", "Weapon recoil/movement labels in the source menu."),
        Item("Tight Spread", "Weapon spread/grouping label."),
        Item("Quick Scope / Fast Swap", "Scope/weapon switching labels."),
        Item("Wallbang / Super Fire Rate / Infinite Ammo", "Combat labels present in the source menu."),
        Item("Hit Effect", "Hit-effect presentation option."),
        Item("Wallhack", "Visibility-through-cover label in the source menu."),
        Item("Visible Color / Occluded Color", "Colors used for visible/covered targets."),
        Item("Magic Bullet", "Target/impact related label in the source menu."),
        Item("Head / Body / Leg Size %", "Target-zone size parameters."),
        Item("Bullet Track", "Projectile/target tracking label in the source menu."),
        Item("Track Range / FOV Radius / Aim Part", "Tracking selection parameters."),
        Item("Track Only While Firing / Track Interval", "Tracking activation/update settings."),
        Item("Weapon Luffy / Gun Soul / Rainbow / Gun Size", "Weapon visual/scale labels."),
        Item("Aimbot / Trigger Mode / Aim Part", "Automatic-aim labels in the source menu."),
        Item("Filter Bots / LOS Check", "Target filtering/line-of-sight labels."),
        Item("Lead / Bullet Speed", "Prediction parameters."),
        Item("Recoil Scale / Smooth", "Recoil/smoothing parameters."),
        Item("FOV Range / Search Distance / Interval", "Target search parameters."),
        Item("Floating Panel", "Settings for the floating menu button/panel."),
        Item("Up / Down / Left / Right", "Moves the floating control."),
        Item("Step - / Step + / Reset Pos", "Changes movement step or restores position."),
        Item("Float Size / BG Color / BG Opacity", "Floating control appearance."),
        Item("Panel Size / Float X / Float Y", "Floating panel size and position."),
        Item("Alive", "Number used by the source overlay for players still alive."),
        Item("Players", "Number used by the source overlay for real players."),
        Item("Bots", "Number used by the source overlay for bots."),
        Item("Crate / Car / Down / Target", "ESP information labels."),
        Item("ADS+Fire / ADS Only / Hip Fire / Fire", "Trigger-mode labels."),
        Item("Head / Chest / Pelvis / Legs / Random", "Selectable body-part labels.")
    )
}
